import express from 'express';
import sanitizeHtml from 'sanitize-html';
import {mountCampaigns} from './campaigns.mjs';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import {randomBytes,randomUUID,timingSafeEqual} from 'node:crypto';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {hashPassword,verifyPassword,validCredentials,digest,canRead,canEdit,parseEntry,projectEntry} from './auth.mjs';
import {entrySchema,settingsSchema} from './validation.mjs';
import seed from './data/seed.json' with {type:'json'};
const cleanRich=e=>{if(e.data.richContent)e.data.richContent=sanitizeHtml(e.data.richContent,{allowedTags:['p','br','strong','em','u','s','h1','h2','h3','h4','blockquote','ul','ol','li','hr','pre','code','span','table','tbody','tr','td','th'],allowedAttributes:{'*':['style'],td:['colspan','rowspan'],th:['colspan','rowspan']},allowedStyles:{'*':{'color':[/^#[0-9a-f]{3,8}$/i,/^rgb\([\d, ]+\)$/],'background-color':[/^#[0-9a-f]{3,8}$/i,/^rgb\([\d, ]+\)$/],'font-family':[/^[a-zA-Z0-9 ,"'-]+$/],'font-size':[/^\d{1,3}(px|pt)$/],'text-align':[/^(left|right|center|justify)$/],'line-height':[/^[123](\.\d+)?$/]}}});return e;};
const base=path.dirname(fileURLToPath(import.meta.url));
const fail=(code,message)=>{const e=new Error(message);e.status=code;throw e;};
const exec=(db,sql,args=[])=>db.execute({sql,args});
export async function createApp({db,production=false,setupKey,rateLimits=true,fichaDb=null}={}){
 const app=express();app.disable('x-powered-by');if(process.env.TRUST_PROXY==='1')app.set('trust proxy',1);
 app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:production?["'self'"]:["'self'","'unsafe-inline'"],styleSrc:["'self'","'unsafe-inline'"],imgSrc:["'self'","data:","blob:"],connectSrc:["'self'",...(production?[]:['ws:'])],frameSrc:["'self'"],objectSrc:["'none'"],upgradeInsecureRequests:production?[]:null}},strictTransportSecurity:production?undefined:false}));
 app.use('/api',(req,res,next)=>{res.set('Cache-Control','no-store');if(!['GET','HEAD','OPTIONS'].includes(req.method)){const origin=req.get('origin');if(req.get('sec-fetch-site')==='cross-site')return res.status(403).json({error:'Origem não permitida.'});if(origin){const expected=process.env.APP_ORIGIN||`${req.protocol}://${req.get('host')}`;if(origin!==expected)return res.status(403).json({error:'Origem não permitida.'});}}next();});
 app.use((req,res,next)=>express.json({limit:req.path==='/api/import'?'45mb':'2mb'})(req,res,next));
 const limit=rateLimits?rateLimit({windowMs:15*60*1000,limit:35,standardHeaders:'draft-8',legacyHeaders:false,message:{error:'Muitas tentativas. Aguarde 15 minutos.'}}):(q,s,n)=>n();
 async function createSession(res,user){const token=randomBytes(32).toString('hex');await exec(db,'DELETE FROM lore_sessions WHERE expires_at < ?',[Date.now()]);await exec(db,'INSERT INTO lore_sessions(token_hash,user_id,expires_at) VALUES(?,?,?)',[digest(token),user.id,Date.now()+7*86400000]);res.cookie('aetheris_lore_session',token,{httpOnly:true,secure:production,sameSite:'lax',path:'/',maxAge:7*86400000});return {id:user.id,username:user.username,role:user.role};}
 app.get('/api/health',(req,res)=>res.json({ok:true}));
 app.get('/api/status',async(req,res)=>res.json({needsSetup:!(await exec(db,"SELECT id FROM lore_users WHERE role='master'")).rows.length}));
 app.post('/api/setup',limit,async(req,res)=>{const b=req.body||{};if(!setupKey||typeof b.setupKey!=='string'||!timingSafeEqual(Buffer.from(digest(b.setupKey)),Buffer.from(digest(setupKey))))fail(403,'Chave de instalação inválida. Consulte o terminal ou SETUP_KEY.');if(!validCredentials(b.username,b.password))fail(400,'Use um nome de 2 a 50 caracteres e uma senha de 12 a 128 caracteres.');if((await exec(db,"SELECT id FROM lore_users WHERE role='master'")).rows.length)fail(409,'O mestre já foi configurado.');const user={id:randomUUID(),username:b.username.trim(),role:'master'};await exec(db,'INSERT INTO lore_users(id,username,password_hash,role) VALUES(?,?,?,?)',[user.id,user.username,await hashPassword(b.password),user.role]);res.json({user:await createSession(res,user)});});
 app.post('/api/invite-register',limit,async(req,res)=>{const b=req.body||{};if(!validCredentials(b.username,b.password)||typeof b.code!=='string')fail(400,'Confira o convite, nome e senha (mínimo 12 caracteres).');const invite=(await exec(db,'SELECT * FROM lore_invites WHERE token_hash=? AND expires_at>?',[digest(b.code.trim()),Date.now()])).rows[0];if(!invite)fail(400,'Convite inválido ou expirado.');const user={id:randomUUID(),username:b.username.trim(),role:'player'};try{await db.batch([{sql:"INSERT INTO lore_users(id,username,password_hash,role) VALUES(?,?,?,'player')",args:[user.id,user.username,await hashPassword(b.password)]},{sql:'INSERT INTO lore_members(campaign_id,user_id) VALUES(?,?)',args:[invite.campaign_id,user.id]}],'write');}catch(e){if(String(e).includes('UNIQUE'))fail(409,'Nome já cadastrado. Entre na conta e aceite o convite em Campanhas.');throw e;}res.json({user:await createSession(res,user)});});
 app.post('/api/login',limit,async(req,res)=>{const {username,password}=req.body||{};if(typeof username!=='string'||typeof password!=='string'||password.length>128)fail(400,'Dados inválidos.');const u=(await exec(db,'SELECT * FROM lore_users WHERE username=?',[username.trim()])).rows[0];const hash=u?.password_hash||'00000000000000000000000000000000:'+ '00'.repeat(64);if(!await verifyPassword(password,hash)||!u)fail(401,'Usuário ou senha incorretos.');res.json({user:await createSession(res,u)});});
 app.use('/api',async(req,res,next)=>{const match=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('aetheris_lore_session='));const token=match?.split('=')[1]||'';const row=(await exec(db,'SELECT u.id,u.username,u.role FROM lore_users u JOIN lore_sessions s ON s.user_id=u.id WHERE s.token_hash=? AND s.expires_at>?',[digest(token),Date.now()])).rows[0];if(!row)return res.status(401).json({error:'Entre para acessar Aetheris.'});row.campaigns=(await exec(db,'SELECT campaign_id FROM lore_members WHERE user_id=?',[row.id])).rows.map(r=>r.campaign_id);req.user=row;req.tokenHash=digest(token);next();});
 const master=(req,res,next)=>req.user.role==='master'?next():res.status(403).json({error:'Acesso exclusivo do mestre.'});
 mountCampaigns(app,db);
 app.get('/api/me',(req,res)=>res.json({user:req.user}));
 app.post('/api/logout',async(req,res)=>{await exec(db,'DELETE FROM lore_sessions WHERE token_hash=?',[req.tokenHash]);res.clearCookie('aetheris_lore_session',{path:'/',secure:production,httpOnly:true,sameSite:'lax'});res.json({ok:true});});
 app.post('/api/password',limit,async(req,res)=>{const u=(await exec(db,'SELECT * FROM lore_users WHERE id=?',[req.user.id])).rows[0];if(typeof req.body.current!=='string'||req.body.current.length>128||!validCredentials(u.username,req.body.password)||!await verifyPassword(req.body.current,u.password_hash))fail(400,'Confira a senha atual e use uma nova senha de pelo menos 12 caracteres.');await db.batch([{sql:'UPDATE lore_users SET password_hash=? WHERE id=?',args:[await hashPassword(req.body.password),u.id]},{sql:'DELETE FROM lore_sessions WHERE user_id=?',args:[u.id]}],'write');res.json({user:await createSession(res,u)});});
 app.get('/api/users',master,async(req,res)=>res.json((await exec(db,'SELECT id,username,role FROM lore_users ORDER BY username')).rows));
 app.post('/api/users',master,async(req,res)=>{const {username,password}=req.body;if(!validCredentials(username,password))fail(400,'Use nome de 2 a 50 caracteres e senha de 12 a 128 caracteres.');const id=randomUUID();try{await exec(db,"INSERT INTO lore_users(id,username,password_hash,role) VALUES(?,?,?,'player')",[id,username.trim(),await hashPassword(password)]);}catch(e){if(String(e).includes('UNIQUE'))fail(409,'Este nome já está em uso.');throw e;}res.json({id,username:username.trim(),role:'player'});});
 app.put('/api/users/:id/password',master,async(req,res)=>{const u=(await exec(db,"SELECT * FROM lore_users WHERE id=? AND role='player'",[req.params.id])).rows[0];if(!u)fail(404,'Jogador não encontrado.');if(!validCredentials(u.username,req.body.password))fail(400,'Use uma senha de 12 a 128 caracteres.');await db.batch([{sql:'UPDATE lore_users SET password_hash=? WHERE id=?',args:[await hashPassword(req.body.password),u.id]},{sql:'DELETE FROM lore_sessions WHERE user_id=?',args:[u.id]}],'write');res.json({ok:true});});
 async function all(){return (await exec(db,'SELECT * FROM lore_entries ORDER BY updated_at DESC,title')).rows.map(parseEntry);}
 async function one(id){const row=(await exec(db,'SELECT * FROM lore_entries WHERE id=?',[id])).rows[0];if(!row)fail(404,'Registro não encontrado.');return parseEntry(row);}
 async function visible(user,entry){const rows=await all();const ids=new Set(rows.filter(e=>canRead(user,e)).map(e=>e.id));return projectEntry(user,entry,ids);}
 app.get('/api/entries',async(req,res)=>{const rows=await all();const ids=new Set(rows.filter(e=>canRead(req.user,e)).map(e=>e.id));res.json(rows.filter(e=>ids.has(e.id)).map(e=>projectEntry(req.user,e,ids)));});
 async function validateSharing(user,e){if(!e.campaign_id){e.visibility='master';e.allowed=[];return;}if(!user.campaigns.includes(e.campaign_id))fail(403,'Você não participa desta campanha.');const members=(await exec(db,'SELECT user_id FROM lore_members WHERE campaign_id=?',[e.campaign_id])).rows.map(r=>r.user_id);e.allowed=e.allowed.filter(id=>members.includes(id));}
 app.post('/api/entries',async(req,res)=>{const parsed=entrySchema.safeParse(req.body);if(!parsed.success)fail(400,'Confira os campos do registro.');const e=cleanRich(parsed.data);await validateSharing(req.user,e);delete e.data.imageId;delete e.data.art;delete e.data.sheetSnapshot;const id=randomUUID();await exec(db,'INSERT INTO lore_entries(id,kind,title,summary,content,secret,data,visibility,allowed,owner_id,campaign_id) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[id,e.kind,e.title,e.summary,e.content,e.secret,JSON.stringify(e.data),e.visibility,JSON.stringify(e.allowed),req.user.id,e.campaign_id]);res.status(201).json(await one(id));});
 app.put('/api/entries/:id',async(req,res)=>{const old=await one(req.params.id);if(!canEdit(req.user,old))fail(403,'Somente o autor pode editar este registro.');const parsed=entrySchema.safeParse(req.body);if(!parsed.success)fail(400,'Confira os campos do registro.');const e=cleanRich(parsed.data);if(e.version!==old.version)fail(409,'O registro mudou em outra janela. Copie seu texto e reabra antes de salvar.');if(e.kind!==old.kind)fail(400,'O tipo do registro não pode mudar.');await validateSharing(req.user,e);e.data.imageId=old.data.imageId;e.data.art=old.data.art;
 const r=await exec(db,"UPDATE lore_entries SET title=?,summary=?,content=?,secret=?,data=?,visibility=?,allowed=?,campaign_id=?,version=version+1,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id=? AND version=?",[e.title,e.summary,e.content,e.secret,JSON.stringify(e.data),e.visibility,JSON.stringify(e.allowed),e.campaign_id,old.id,old.version]);if(!r.rowsAffected)fail(409,'O registro mudou. Reabra antes de salvar.');res.json(await one(old.id));});
 app.delete('/api/entries/:id',async(req,res)=>{const e=await one(req.params.id);if(!canEdit(req.user,e))fail(403,'Somente o autor pode excluir.');await db.batch([{sql:'DELETE FROM lore_assets WHERE entry_id=?',args:[e.id]},{sql:'DELETE FROM lore_entries WHERE id=?',args:[e.id]}],'write');res.json({ok:true});});
 app.get('/api/settings',async(req,res)=>{const row=(await exec(db,"SELECT value FROM lore_settings WHERE key='config'")).rows[0];res.json({...{sheetSiteUrl:'https://aetherissistema2.onrender.com',...JSON.parse(row?.value||'{}')},fichaConnected:!!fichaDb});});
 app.put('/api/settings',master,async(req,res)=>{const p=settingsSchema.safeParse(req.body);if(!p.success)fail(400,'Endereço inválido.');await exec(db,"INSERT INTO lore_settings(key,value) VALUES('config',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",[JSON.stringify(p.data)]);res.json({...p.data,fichaConnected:!!fichaDb});});
 app.post('/api/entries/:id/image',express.raw({type:['image/png','image/jpeg','image/webp'],limit:'5mb'}),async(req,res)=>{const e=await one(req.params.id);if(!canEdit(req.user,e))fail(403,'Somente o autor pode enviar imagens.');if(!Buffer.isBuffer(req.body)||req.body.length<12)fail(400,'Envie PNG, JPEG ou WebP até 5 MB.');const b=req.body;let mime=b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))?'image/png':b[0]===255&&b[1]===216?'image/jpeg':b.toString('ascii',0,4)==='RIFF'&&b.toString('ascii',8,12)==='WEBP'?'image/webp':null;if(!mime)fail(400,'Imagem inválida.');const id=randomUUID();const r=await db.batch([{sql:'INSERT INTO lore_assets(id,entry_id,mime,bytes) VALUES(?,?,?,?)',args:[id,e.id,mime,b]},{sql:'UPDATE lore_entries SET data=?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND version=?',args:[JSON.stringify({...e.data,imageId:id}),e.id,e.version]}],'write');if(!r[1].rowsAffected)fail(409,'O registro mudou. Reabra antes de enviar a imagem.');res.json(await one(e.id));});
 app.get('/api/assets/:id',async(req,res)=>{const asset=(await exec(db,'SELECT * FROM lore_assets WHERE id=?',[req.params.id])).rows[0];if(!asset)fail(404,'Imagem não encontrada.');const e=await one(asset.entry_id);if(!canRead(req.user,e))fail(404,'Imagem não encontrada.');res.type(asset.mime).send(Buffer.from(asset.bytes));});
 app.get('/api/art/:name',async(req,res)=>{if(!/^[a-z0-9-]+\.jpg$/.test(req.params.name))fail(404,'Imagem não encontrada.');const entries=await all();if(!entries.some(e=>e.data.art===req.params.name&&canRead(req.user,e)))fail(404,'Imagem não encontrada.');res.sendFile(path.join(base,'data/art',req.params.name));});
 app.get('/api/library/:name',master,(req,res)=>{const file={lore:'livro-de-lore.pdf',grimorio:'grimorio.pdf'}[req.params.name];if(!file)fail(404,'Livro não encontrado.');res.sendFile(path.join(base,'data/library',file));});
 app.get('/api/export',async(req,res)=>{const owned=(await all()).filter(e=>canEdit(req.user,e));const ownedIds=new Set(owned.map(e=>e.id));const assets=(await exec(db,'SELECT * FROM lore_assets')).rows.filter(a=>ownedIds.has(a.entry_id)).map(a=>({...a,bytes:Buffer.from(a.bytes).toString('base64')}));res.set('Content-Disposition','attachment; filename="aetheris-backup.json"').json({format:'aetheris-lore',version:1,date:new Date().toISOString(),entries:owned,assets,settings:[]});});
 app.post('/api/import',express.json({limit:'45mb'}),async(req,res)=>{const backup=req.body;if(backup?.format!=='aetheris-lore'||backup.version!==1||!Array.isArray(backup.entries)||backup.entries.length>5000||!Array.isArray(backup.assets)||backup.assets.length>500)fail(400,'Backup inválido.');const statements=[];for(const raw of backup.entries){const p=entrySchema.safeParse(raw);if(!p.success||!p.data.id)fail(400,'Há um registro inválido no backup.');const e=cleanRich(p.data);if(req.user.role!=='master')delete e.data.art;const existing=(await exec(db,'SELECT owner_id FROM lore_entries WHERE id=?',[e.id])).rows[0];if(existing&&existing.owner_id!==req.user.id&&!(req.user.role==='master'&&!existing.owner_id))fail(403,'O backup contém IDs pertencentes a outro acervo.');statements.push({sql:'INSERT OR IGNORE INTO lore_entries(id,kind,title,summary,content,secret,data,visibility,allowed,owner_id) VALUES(?,?,?,?,?,?,?,?,?,?)',args:[e.id,e.kind,e.title,e.summary,e.content,e.secret,JSON.stringify(e.data),'master','[]',req.user.id]});}for(const a of backup.assets){if(typeof a.id!=='string'||typeof a.entry_id!=='string'||!backup.entries.some(e=>e.id===a.entry_id)||!['image/png','image/jpeg','image/webp'].includes(a.mime)||typeof a.bytes!=='string'||a.bytes.length>7000000)fail(400,'Imagem inválida no backup.');statements.push({sql:'INSERT OR IGNORE INTO lore_assets(id,entry_id,mime,bytes) VALUES(?,?,?,?)',args:[a.id,a.entry_id,a.mime,Buffer.from(a.bytes,'base64')]});}if(statements.length)await db.batch(statements,'write');res.json({ok:true,message:'Registros ausentes importados como privados. Os existentes foram preservados.'});});
 app.get('/api/fichas',master,async(req,res)=>{if(!fichaDb)fail(503,'Configure FICHA_DATABASE_URL e FICHA_AUTH_TOKEN no servidor.');const result=await fichaDb.execute('SELECT sheets.id,sheets.name,sheets.data,sheets.version,users.username FROM sheets JOIN users ON users.id=sheets.user_id ORDER BY sheets.updated_at DESC LIMIT 500');res.json(result.rows.map(r=>{let p={};try{p=JSON.parse(r.data);}catch{}return {id:String(r.id),name:r.name,username:r.username,race:p.state?.race||'',region:p.fields?.['f-regiao']||'',occupation:p.state?.profession||'',level:p.state?.level||1,version:Number(r.version)};}));});
 app.use('/api',(req,res)=>res.status(404).json({error:'Rota não encontrada.'}));
 app.use((err,req,res,next)=>{if(res.headersSent)return next(err);const status=err.status||500;if(status>=500)console.error('Falha na API:',err.message);res.status(status).json({error:status===413?'Arquivo muito grande.':status>=500?'Não foi possível concluir. Tente novamente.':err.message});});
 return app;
}
export async function seedDatabase(db){const marker=await exec(db,"SELECT value FROM lore_settings WHERE key='seed-v1'");if(marker.rows.length)return;await db.batch([...seed.map(e=>({sql:'INSERT OR IGNORE INTO lore_entries(id,kind,title,summary,content,secret,data,visibility,allowed,owner_id) VALUES(?,?,?,?,?,?,?,?,?,?)',args:[e.id,e.kind,e.title,e.summary,e.content,e.secret||'',JSON.stringify(e.data||{}),'master','[]','']})),{sql:"INSERT OR IGNORE INTO lore_settings(key,value) VALUES('seed-v1','1')",args:[]}],'write');}
