import {randomUUID,randomBytes} from 'node:crypto';
import {digest} from './auth.mjs';
export function mountCampaigns(app,db){
 const run=(sql,args=[])=>db.execute({sql,args});
 const member=async(req,res,next)=>{const m=(await run('SELECT * FROM lore_members WHERE campaign_id=? AND user_id=?',[req.params.id,req.user.id])).rows[0];if(!m)return res.status(404).json({error:'Campanha não encontrada.'});next();};
 const owner=async(req,res,next)=>{const c=(await run('SELECT * FROM lore_campaigns WHERE id=? AND owner_id=?',[req.params.id,req.user.id])).rows[0];if(!c)return res.status(403).json({error:'Somente o criador gerencia a campanha.'});next();};
 app.get('/api/campaigns',async(req,res)=>{const list=(await run('SELECT c.* FROM lore_campaigns c JOIN lore_members m ON c.id=m.campaign_id WHERE m.user_id=? ORDER BY c.created_at DESC',[req.user.id])).rows;for(const c of list)c.members=(await run('SELECT u.id,u.username FROM lore_users u JOIN lore_members m ON u.id=m.user_id WHERE m.campaign_id=?',[c.id])).rows;res.json(list);});
 app.post('/api/campaigns',async(req,res)=>{const {name,description=''}=req.body||{};if(typeof name!=='string'||!name.trim()||name.length>120||typeof description!=='string'||description.length>3000)return res.status(400).json({error:'Informe um nome de até 120 caracteres e descrição de até 3.000.'});const id=randomUUID();await db.batch([{sql:'INSERT INTO lore_campaigns(id,name,description,owner_id) VALUES(?,?,?,?)',args:[id,name.trim(),description,req.user.id]},{sql:'INSERT INTO lore_members(campaign_id,user_id) VALUES(?,?)',args:[id,req.user.id]}],'write');res.status(201).json({id});});
 app.post('/api/campaigns/join',async(req,res)=>{if(typeof req.body?.code!=='string')return res.status(400).json({error:'Informe o código de convite.'});const invite=(await run('SELECT * FROM lore_invites WHERE token_hash=? AND expires_at>?',[digest(req.body.code.trim()),Date.now()])).rows[0];if(!invite)return res.status(400).json({error:'Convite inválido ou expirado.'});await run('INSERT OR IGNORE INTO lore_members(campaign_id,user_id) VALUES(?,?)',[invite.campaign_id,req.user.id]);res.json({ok:true});});
 app.post('/api/campaigns/:id/invite',owner,async(req,res)=>{const code=randomBytes(24).toString('hex');await db.batch([{sql:'DELETE FROM lore_invites WHERE campaign_id=?',args:[req.params.id]},{sql:'INSERT INTO lore_invites(token_hash,campaign_id,expires_at) VALUES(?,?,?)',args:[digest(code),req.params.id,Date.now()+7*86400000]}],'write');res.json({code});});
 app.delete('/api/campaigns/:id/invite',owner,async(req,res)=>{await run('DELETE FROM lore_invites WHERE campaign_id=?',[req.params.id]);res.json({ok:true});});
 app.delete('/api/campaigns/:id/members/:userId',member,async(req,res)=>{const c=(await run('SELECT * FROM lore_campaigns WHERE id=?',[req.params.id])).rows[0];if(req.params.userId===c.owner_id)return res.status(400).json({error:'O criador não pode sair da própria campanha.'});if(req.user.id!==c.owner_id&&req.user.id!==req.params.userId)return res.status(403).json({error:'Sem permissão.'});await run('DELETE FROM lore_members WHERE campaign_id=? AND user_id=?',[c.id,req.params.userId]);res.json({ok:true});});
}
