import {useEffect,useState} from 'react';
import {BookOpen,Feather,Map as MapIcon,Users,GitBranch,Castle,Sparkles,Plus,Shield,ScrollText,Search,Settings as SettingsIcon,LogOut,Library,ArrowUpRight,Eye,ChevronRight} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarFooter,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {Input} from '@/components/ui/input';
import {api,labels,singular,emptyEntry,imageFor,type Entry,type Kind,type Person,type Settings,type Campaign} from './types';
import {Choice,Field,Visibility,Empty} from './ui';
import Auth from './Auth';
import Campaigns from './Campaigns';
import Detail from './Detail';
import SettingsPage from './Settings';
const nav=[{id:'campaigns',label:'Campanhas',icon:Users},{id:'overview',label:'Visão geral',icon:BookOpen},{id:'lore',label:'Enciclopédia',icon:ScrollText},{id:'script',label:'Roteiros & escrita',icon:Feather},{id:'character',label:'Personagens',icon:Users},{id:'npc',label:'NPCs & divindades',icon:Sparkles},{id:'city',label:'Cidades & regiões',icon:Castle},{id:'map',label:'Atlas & mapas',icon:MapIcon},{id:'lineage',label:'Árvores genealógicas',icon:GitBranch},{id:'library',label:'Livros de referência',icon:Library}];
function CloseMobileNavigation({view,selected}:{view:string;selected:string|null}){const {setOpenMobile}=useSidebar();useEffect(()=>{setOpenMobile(false)},[view,selected,setOpenMobile]);return null;}
export default function App(){
 const [user,setUser]=useState<Person|null>(null),[ready,setReady]=useState(false),[needsSetup,setNeedsSetup]=useState(false),[entries,setEntries]=useState<Entry[]>([]),[settings,setSettings]=useState<Settings>({}),[people,setPeople]=useState<Person[]>([]),[view,setView]=useState('overview'),[selected,setSelected]=useState<string|null>(null),[query,setQuery]=useState(''),[tag,setTag]=useState(''),[filter,setFilter]=useState(''),[createOpen,setCreateOpen]=useState(false),[kind,setKind]=useState<Kind>('lore'),[title,setTitle]=useState(''),[busy,setBusy]=useState(false),[loadError,setLoadError]=useState(''),[preview,setPreview]=useState(false),[dirty,setDirty]=useState(false);
 useEffect(()=>{window.scrollTo({top:0})},[view,selected]);
 const [campaigns,setCampaigns]=useState<Campaign[]>([]),[campaignFilter,setCampaignFilter]=useState('');
 const master=user?.role==='master'&&!preview;
 async function reload(){try{const [e,s]=await Promise.all([api('/entries'),api('/settings')]);setEntries(e);setSettings(s);setCampaigns(await api('/campaigns'));setLoadError('');if(user?.role==='master')setPeople(await api('/users'));}catch(e:any){setLoadError(e.message)}}
 useEffect(()=>{(async()=>{try{const status=await api('/status');setNeedsSetup(status.needsSetup);try{const d=await api('/me');setUser(d.user);}catch{}}catch(e:any){setLoadError(e.message)}finally{setReady(true)}})()},[]);
 useEffect(()=>{if(user)void reload();},[user]);
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[dirty]);
 function proceed(fn:()=>void){if(!dirty||window.confirm('Há alterações não salvas. Deseja descartá-las?')){setDirty(false);fn();}}
 function go(v:string){proceed(()=>{setView(v);setSelected(null);setCampaignFilter('');setQuery('');setTag('');setFilter('')})}
 const publicIds=new Set(entries.filter(e=>!!e.campaign_id&&e.visibility==='all').map(e=>e.id));
 const visible=preview?entries.filter(e=>publicIds.has(e.id)).map(e=>{const nodes=e.data.nodes?.filter(n=>!n.hidden&&(!n.entryId||publicIds.has(n.entryId)));const nodeIds=new Set(nodes?.map(n=>n.id));return {...e,secret:'',allowed:[],data:{...e.data,sheetSnapshot:undefined,related:e.data.related?.filter(id=>publicIds.has(id)),pins:e.data.pins?.filter(p=>!p.hidden&&(!p.entryId||publicIds.has(p.entryId))),nodes,edges:e.data.edges?.filter(edge=>nodeIds.has(edge.from)&&nodeIds.has(edge.to))}}}):entries;
 const current=visible.find(e=>e.id===selected);
 const cards=visible.filter(e=>(view==='overview'||e.kind===view)&&(!campaignFilter||e.campaign_id===campaignFilter)&&(!query||`${e.title} ${e.summary} ${e.content} ${(e.data.tags||[]).join(' ')}`.toLowerCase().includes(query.toLowerCase()))&&(!tag||e.data.tags?.includes(tag))&&(!filter||e.visibility===filter));
 function openEntry(e:Entry){proceed(()=>{setView(e.kind);setSelected(e.id)})}
 function saved(e:Entry){setEntries(old=>[e,...old.filter(x=>x.id!==e.id)]);setDirty(false)}
 function newEntry(k?:Kind){setKind(k||'lore');setTitle('');setCreateOpen(true)}
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(ctx.registerTool({name:'search_aetheris_lore',title:'Pesquisar no arquivo de Aetheris',description:'Pesquisa somente os registros disponíveis na sessão atual, sem alterar conteúdo.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof(input as any).query!=='string')throw new Error('Informe query como texto.');const q=(input as any).query.toLowerCase();return visible.filter(e=>`${e.title} ${e.summary}`.toLowerCase().includes(q)).map(e=>({id:e.id,title:e.title,kind:e.kind,summary:e.summary}));}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[entries,preview]);
 if(!ready)return <div className="loading">Abrindo o arquivo…</div>;
 if(!user)return <><Auth needsSetup={needsSetup} onLogin={u=>{setUser(u);setNeedsSetup(false)}}/>{loadError&&<p role="alert" className="error floating-error">{loadError}</p>}</>;
 return <><Toaster theme="dark" richColors/><SidebarProvider><CloseMobileNavigation view={view} selected={selected}/><Sidebar><SidebarHeader><button className="brand" onClick={()=>go('overview')} aria-label="Ir para visão geral"><Sparkles/><div>AETHERIS<small>CRÔNICAS</small></div></button></SidebarHeader><SidebarContent><p className="nav-label">SEU UNIVERSO</p><SidebarMenu>{nav.filter(n=>n.id!=='library'||master).map(({id,label,icon:Icon})=><SidebarMenuItem key={id}><SidebarMenuButton isActive={view===id} onClick={()=>go(id)}><Icon/><span>{label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><p className="nav-label">SUA MESA</p><SidebarMenu><SidebarMenuItem><SidebarMenuButton isActive={view==='settings'} onClick={()=>go('settings')}><SettingsIcon/><span>{master?'Administração':'Conta & backup'}</span></SidebarMenuButton></SidebarMenuItem>{settings.sheetSiteUrl&&<SidebarMenuItem><SidebarMenuButton asChild><a href={settings.sheetSiteUrl} target="_blank" rel="noreferrer"><ArrowUpRight/><span>Fichas técnicas</span></a></SidebarMenuButton></SidebarMenuItem>}</SidebarMenu></SidebarContent><SidebarFooter><div className="profile"><span className="avatar">{user.username.slice(0,1).toUpperCase()}</span><div><strong>{user.username}</strong><small>{user.role==='master'?'Mestre de Aetheris':'Jogador'}</small></div><button className="icon-button" aria-label="Sair" onClick={()=>proceed(async()=>{try{await api('/logout',{method:'POST'});setUser(null);setEntries([]);setSelected(null);setPreview(false)}catch(e:any){toast.error(e.message)}})}><LogOut size={17}/></button></div></SidebarFooter></Sidebar><main className="workspace"><header className="topbar"><SidebarTrigger/><span>Aetheris Crônicas <ChevronRight size={13} style={{display:'inline'}}/> {nav.find(n=>n.id===view)?.label||'Sua mesa'}</span><div className="top-actions">{user.role==='master'&&<button className="text-button" onClick={()=>proceed(()=>{setPreview(!preview);setSelected(null);setView('overview')})}><Eye size={15}/>{preview?'Voltar ao mestre':'Visão dos jogadores'}</button>}<span className="badge"><Shield size={12}/>{preview?'Prévia':'Seu acervo'}</span></div></header>{preview&&<div className="preview-banner">Prévia das páginas compartilhadas com campanhas. Segredos e liberações individuais ficam ocultos nesta prévia.</div>}{loadError&&<div className="error error-bar" role="alert">{loadError} <button onClick={reload}>Tentar novamente</button></div>}
 {current?<Detail key={current.id} entry={current} entries={visible} user={user} master={!preview&&(current.owner_id===user.id||(!current.owner_id&&user.role==='master'))} campaigns={campaigns} preview={preview} people={campaigns.find(c=>c.id===current.campaign_id)?.members.map(m=>({...m,role:'player' as const}))||[]} settings={settings} onSave={saved} onDirty={setDirty} onBack={()=>proceed(()=>setSelected(null))} onOpen={openEntry} onDelete={id=>{setEntries(entries.filter(e=>e.id!==id));setSelected(null);setDirty(false)}}/>:view==='campaigns'?<Campaigns campaigns={campaigns} user={user} reload={reload} onOpen={id=>{go('overview');setCampaignFilter(id)}}/>:view==='settings'?<SettingsPage user={user} master={!!master} settings={settings} people={people} reload={reload} setSettings={setSettings} onImport={reload}/>:view==='library'&&master?<div className="page"><p className="eyebrow">FONTES DO SEU UNIVERSO</p><h1>Livros de referência</h1><p>Os livros completos ficam disponíveis apenas para o mestre. Revele os resumos editáveis pela enciclopédia.</p><div className="cards library-cards">{[{id:'lore',title:'Livro de Lore',text:'Cosmologia, deuses, regiões, raças e conflitos. 61 páginas.'},{id:'grimorio',title:'Grimório de Aetheris',text:'Ficha técnica, poderes personalizados e bênçãos divinas.'}].map(b=><a className="panel book-card" href={'/api/library/'+b.id} target="_blank" rel="noreferrer" key={b.id}><Library size={42}/><h2>{b.title}</h2><p>{b.text}</p><span>Abrir livro <ArrowUpRight size={15}/></span></a>)}</div><p className="hint">O Livro de Lore é uma cópia visual otimizada para leitura. O texto inicial da enciclopédia contém resumos com indicação de página; não substitui o livro completo.</p></div>:<div className="page"><div className="heading"><div><p className="eyebrow">{view==='overview'?(campaignFilter?'ACERVO DA CAMPANHA':'SEU UNIVERSO PARTICULAR'):'PÁGINAS DO SEU UNIVERSO'}</p><h1>{view==='overview'?(campaignFilter?campaigns.find(c=>c.id===campaignFilter)?.name:'Toda história merece um mundo.'):labels[view as Kind]}</h1><p>{view==='overview'?'Histórias, lugares e destinos de um mundo suspenso.':`${visible.filter(e=>e.kind===view).length} registros · ${master?'Organize, conecte e escolha o que revelar.':'O conhecimento que a sua jornada reuniu.'}`}</p></div>{!preview&&<button className="primary" onClick={()=>newEntry(view==='overview'?undefined:view as Kind)}><Plus size={18}/> Criar registro</button>}</div>
 {view==='overview'&&!query&&<><div className="overview-grid"><section className="panel feature"><p className="eyebrow">UM UNIVERSO, INFINITAS POSSIBILIDADES</p><h2>Escreva o que<br/>ainda não existe.</h2><p>Um arquivo para guardar o que foi vivido — e preparar tudo o que ainda pode acontecer.</p><div className="divider"/><div className="stats">{[{label:'Personagens',kind:'character'},{label:'Lugares',kind:'city'},{label:'Roteiros',kind:'script'}].map(s=><button key={s.kind} onClick={()=>go(s.kind)}><strong>{visible.filter(e=>e.kind===s.kind).length.toString().padStart(2,'0')}</strong><span>{s.label}</span></button>)}</div></section><section className="panel desk"><p className="eyebrow">NA SUA ESCRIVANINHA</p><h2>{master?'Prepare a próxima história.':'Registre a sua jornada.'}</h2><p>{master?'Dos primeiros ganchos aos segredos que mudarão a campanha.':'Crie a história do seu personagem e anote suas descobertas.'}</p><div className="quick-actions"><button onClick={()=>go('script')}><Feather size={19}/><span>Roteiros & anotações<small>Cenas, pistas e acontecimentos</small></span><ChevronRight size={16}/></button><button onClick={()=>go('character')}><Users size={19}/><span>Histórias de personagens<small>Origens, desejos e vínculos</small></span><ChevronRight size={16}/></button><button onClick={()=>go('map')}><MapIcon size={19}/><span>Explore o atlas<small>Mapas e lugares da campanha</small></span><ChevronRight size={16}/></button></div></section></div><div className="section-row"><h2 className="section-title">Nas páginas do mundo</h2><span className="hint">{visible.length} registros no arquivo</span></div></>}
 <div className="filterbar"><div className="search"><Search size={17}/><Input aria-label="Buscar no arquivo" placeholder="Buscar nome, lugar ou trecho da história…" value={query} onChange={e=>setQuery(e.target.value)}/></div>{view!=='overview'&&<Choice label="Categoria" value={tag} onChange={setTag} options={[{value:'',label:'Todas as categorias'},...Array.from(new Set(visible.filter(e=>e.kind===view).flatMap(e=>e.data.tags||[]))).map(t=>({value:t,label:t}))]}/>} {master&&<Choice label="Visibilidade" value={filter} onChange={setFilter} options={[{value:'',label:'Todo o acervo'},{value:'master',label:'Reservados'},{value:'all',label:'Revelados'},{value:'selected',label:'Grupo selecionado'}]}/>}</div>
 {cards.length?<div className={'cards '+(view==='script'?'script-cards':'')}>{(view==='overview'&&!query?cards.slice(0,9):cards).map((e,i)=>{const Icon=nav.find(n=>n.id===e.kind)?.icon||BookOpen;return <button className={'panel lore-card '+(imageFor(e)?'with-image':'')} key={e.id} onClick={()=>openEntry(e)}>{imageFor(e)?<img src={imageFor(e)} alt="" loading="lazy"/>:<><span className="folio">{String(i+1).padStart(2,'0')}</span><Icon size={25}/></>}<div className="card-body"><div className="card-category">{e.data.tags?.[0]||singular[e.kind]}</div><h3>{e.title}</h3><p>{e.summary||'Uma nova página da sua história.'}</p><div className="card-bottom"><Visibility value={e.visibility}/>{e.kind==='script'&&<small>{e.data.status||'Rascunho'}</small>}</div></div></button>})}</div>:<Empty title={query?'Nenhum registro encontrado.':'Uma página ainda em branco.'} description={query?'Experimente outro termo ou remova os filtros.':master?'Crie o primeiro registro desta coleção.':preview?'O mestre ainda não revelou conteúdo para todos.':'Crie registros de qualquer categoria. Seu acervo é privado até você escolher compartilhar em uma campanha.'}>{!preview&&<button className="primary" onClick={()=>newEntry(view==='overview'?'lore':view as Kind)}><Plus size={17}/> Criar primeiro registro</button>}</Empty>}
 </div>}</main></SidebarProvider>
 <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent><DialogHeader><DialogTitle>Uma nova página</DialogTitle><DialogDescription>Dê um nome ao registro. Você poderá completar todos os detalhes a seguir.</DialogDescription></DialogHeader><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const record=await api('/entries',{method:'POST',body:JSON.stringify({...emptyEntry(kind),title,campaign_id:campaignFilter})});saved(record);setCreateOpen(false);setView(kind);setSelected(record.id);toast.success('Registro criado.');}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}}><Choice label="Tipo de registro" value={kind} onChange={v=>setKind(v as Kind)} options={Object.keys(singular).map(k=>({value:k,label:singular[k as Kind]}))}/><Field label="Nome ou título" value={title} onChange={setTitle} autoFocus required maxLength={180}/><p className="hint">Começa privado. Você decide se quer compartilhar em uma campanha.</p><button className="primary full" disabled={busy||!title.trim()}>{busy?'Criando…':'Criar registro'}</button></form></DialogContent></Dialog>
 </>;
}
