import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,Save,Trash2,Lock,BookOpen,ExternalLink,Upload,Feather,Maximize2,Minimize2,Link as LinkIcon} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Textarea} from '@/components/ui/textarea';
import {toast} from 'sonner';
import {api,imageFor,singular,type Entry,type Person,type Settings,type Campaign} from './types';
import {Field,Choice,Visibility,Prose} from './ui';
import RichEditor,{RichReading} from './RichEditor';
import {Atlas,FamilyTree} from './Boards';
type Props={campaigns:Campaign[];entry:Entry;entries:Entry[];user:Person;master:boolean;preview:boolean;people:Person[];settings:Settings;onSave:(e:Entry)=>void;onDirty:(v:boolean)=>void;onBack:()=>void;onOpen:(e:Entry)=>void;onDelete:(id:string)=>void};
export default function Detail({campaigns,entry,entries,user,master,preview,people:unusedPeople,settings,onSave,onDirty,onBack,onOpen,onDelete}:Props){const [draft,setDraft]=useState<Entry>(structuredClone(entry)),[busy,setBusy]=useState(false),[deleting,setDeleting]=useState(false),[focus,setFocus]=useState(false),[tab,setTab]=useState('read'),[saveError,setSaveError]=useState(''),[tagsText,setTagsText]=useState((entry.data.tags||[]).join(', '));const area=useRef<HTMLTextAreaElement>(null);const editable=!preview&&master;const dirty=JSON.stringify(draft)!==JSON.stringify(entry);useEffect(()=>{onDirty(dirty)},[dirty,onDirty]);
 const patch=(p:Partial<Entry>)=>setDraft(e=>({...e,...p}));const data=(d:Entry['data'])=>patch({data:d});const field=(k:string,v:any)=>data({...draft.data,[k]:v});
 async function save(){if(busy||!editable)return;setBusy(true);setSaveError('');try{const e=await api('/entries/'+draft.id,{method:'PUT',body:JSON.stringify(draft)});setDraft(e);onSave(e);toast.success('Alterações salvas.')}catch(e:any){setSaveError(e.message);toast.error(e.message)}finally{setBusy(false)}}
 const saveRef=useRef(save);saveRef.current=save;useEffect(()=>{const listener=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();void saveRef.current()}};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener)},[]);
 async function upload(file:File){if(file.size>5*1024*1024){toast.error('Use uma imagem de até 5 MB.');return;}if(dirty){toast.error('Salve suas alterações antes de enviar uma imagem.');return;}setBusy(true);try{const r=await api('/entries/'+entry.id+'/image',{method:'POST',headers:{'Content-Type':file.type},body:file});setDraft(r);onSave(r);toast.success('Imagem guardada.')}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 function insert(before:string,after=''){const a=area.current;if(!a)return;const start=a.selectionStart,end=a.selectionEnd;patch({content:draft.content.slice(0,start)+before+draft.content.slice(start,end)+after+draft.content.slice(end)});requestAnimationFrame(()=>{a.focus();a.setSelectionRange(start+before.length,end+before.length)})}
 const sheetUrl=draft.data.sheetUrl||settings.sheetSiteUrl;
 const personal=['character','npc'].includes(entry.kind);const people=(campaigns.find(c=>c.id===draft.campaign_id)?.members||[]).map(m=>({...m,role:'player'}));
 return <div className={'page detail-page '+(focus?'focus-mode':'')}><div className="detail-top"><button className="text-button" onClick={onBack}><ArrowLeft size={16}/> Voltar ao acervo</button><div className="button-row"><span className={'save-status '+(dirty?'unsaved':'')}>{dirty?'Alterações não salvas':'Tudo salvo'}</span>{editable&&<button className="primary" onClick={save} disabled={busy||!dirty||!draft.title.trim()}><Save size={16}/>{busy?'Salvando…':'Salvar'}</button>}{master&&<button className="icon-button danger" aria-label="Excluir registro" onClick={()=>setDeleting(true)}><Trash2 size={17}/></button>}</div></div>{saveError&&<p role="alert" className="error">{saveError} Seu texto permanece nesta tela.</p>}<div className="record-heading"><p className="eyebrow">{singular[entry.kind]} {draft.data.tags?.length?` / ${draft.data.tags.join(' · ')}`:''}</p><h1>{entry.title}</h1><div className="record-meta"><Visibility value={entry.visibility}/>{entry.data.source&&<span>{entry.data.source} · p. {entry.data.sourcePage}</span>}</div></div>
 <div className="detail-grid"><section className="record-main"><Tabs value={tab} onValueChange={setTab}><TabsList variant="line" className="record-tabs"><TabsTrigger value="read"><BookOpen size={16}/> Leitura</TabsTrigger>{editable&&<TabsTrigger value="edit"><Feather size={16}/> Escrever</TabsTrigger>}{['map','lineage'].includes(entry.kind)&&<TabsTrigger value="board">{entry.kind==='map'?'Mapa interativo':'Árvore de vínculos'}</TabsTrigger>}{master&&<TabsTrigger value="secret"><Lock size={15}/> Notas privadas</TabsTrigger>}</TabsList>
 <TabsContent value="read"><article className="reading-panel">{imageFor(draft)&&entry.kind!=='map'&&<img className={"record-art "+(draft.data.portrait?"portrait-art":"")} src={imageFor(draft)} alt={draft.title}/>}<p className="lead">{draft.summary}</p>{personal&&<dl className="identity-grid">{[['Raça',draft.data.race],['Origem',draft.data.region],['Ocupação',draft.data.occupation]].filter(x=>x[1]).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>}{draft.data.richContent?<RichReading html={draft.data.richContent}/>:<Prose text={draft.content||'Esta história ainda não foi escrita.'}/>}{personal&&[['Aparência',draft.data.appearance],['Personalidade',draft.data.personality],['Desejos & motivações',draft.data.motivation]].filter(x=>x[1]).map(([label,text])=><section key={label}><h2>{label}</h2><Prose text={text||''}/></section>)}{master&&draft.data.document&&<a className="source-link" href={'/api/library/'+draft.data.document+'#page='+(draft.data.sourcePage||1)} target="_blank" rel="noreferrer"><BookOpen size={15}/> Consultar página no livro <ExternalLink size={13}/></a>}{editable&&<button className="secondary" onClick={()=>setTab('edit')}><Feather size={15}/> Continuar escrevendo</button>}</article></TabsContent>
 {editable&&<TabsContent value="edit"><div className="editor-panel"><Field label="Nome ou título" value={draft.title} onChange={v=>patch({title:v})} maxLength={180}/><Field label="Resumo" value={draft.summary} onChange={v=>patch({summary:v})} multiline rows={2} maxLength={2000}/>{personal&&<><div className="two-fields"><Field label="Raça" value={draft.data.race||''} onChange={v=>field('race',v)} list="races"/><datalist id="races">{['Humanos','Lupir','Feliri','Avaris','Reptilianos','Veylans','Ethereals','Ossídeos'].map(r=><option key={r}>{r}</option>)}</datalist><Field label="Origem / região" value={draft.data.region||''} onChange={v=>field('region',v)}/></div><Field label="Ocupação ou papel na história" value={draft.data.occupation||''} onChange={v=>field('occupation',v)}/></>}{entry.kind==='script'&&<Choice label="Etapa do roteiro" value={draft.data.status||'Rascunho'} onChange={v=>field('status',v)} options={['Rascunho','Preparado','Em jogo','Concluído'].map(x=>({value:x,label:x}))}/>}
 <div className="editor-toolbar"><button className="focus-button" onClick={()=>setFocus(!focus)}>{focus?<Minimize2 size={15}/>:<Maximize2 size={15}/>} {focus?'Sair do foco':'Modo foco'}</button><span className="hint">Salvar: Ctrl / ⌘ + S</span></div><RichEditor html={draft.data.richContent} text={draft.content} onChange={(html,text)=>patch({content:text,data:{...draft.data,richContent:html}})}/>
 {personal&&<><Field label="Aparência" value={draft.data.appearance||''} onChange={v=>field('appearance',v)} multiline rows={3}/><Field label="Personalidade" value={draft.data.personality||''} onChange={v=>field('personality',v)} multiline rows={3}/><Field label="Desejos, medos e motivações" value={draft.data.motivation||''} onChange={v=>field('motivation',v)} multiline rows={3}/></>}
 </div></TabsContent>}
 <TabsContent value="board"><section className="panel board-panel">{entry.kind==='map'?<Atlas entry={draft} entries={entries} editable={editable} onChange={data} onUpload={upload} onOpen={onOpen}/>:entry.kind==='lineage'?<FamilyTree entry={draft} entries={entries} editable={editable} onChange={data} onOpen={onOpen}/>:null}</section></TabsContent>
 {master&&<TabsContent value="secret"><section className="panel secret-panel"><div className="secret-heading"><Lock size={20}/><h2>O que só você sabe</h2></div><p>Estas notas são exclusivas do autor, mesmo ao compartilhar o registro.</p><Textarea aria-label="Notas privadas" rows={16} value={draft.secret} onChange={e=>patch({secret:e.target.value})} placeholder="Identidades ocultas, planos, traições e consequências…" maxLength={50000}/></section></TabsContent>}</Tabs></section>
 <aside className="record-aside">{master&&<section className="panel"><p className="eyebrow">COMPARTILHAMENTO</p><Choice label="Campanha" value={draft.campaign_id||''} onChange={v=>patch({campaign_id:v,visibility:'master',allowed:[]})} options={[{value:'',label:'Só no meu acervo'},...campaigns.map(c=>({value:c.id,label:c.name}))]}/><Choice disabled={!draft.campaign_id} label="Quem pode descobrir?" value={draft.visibility} onChange={v=>patch({visibility:v as Entry['visibility']})} options={[{value:'master',label:'Somente eu'},{value:'all',label:'Toda a campanha'},{value:'selected',label:'Participantes selecionados'}]}/>{draft.visibility==='selected'&&<div className="check-list">{people.filter(p=>p.role==='player').length?people.filter(p=>p.role==='player').map(p=><label key={p.id}><Checkbox checked={draft.allowed.includes(p.id)} onCheckedChange={v=>patch({allowed:v?[...draft.allowed,p.id]:draft.allowed.filter(x=>x!==p.id)})}/>{p.username}</label>):<p className="hint">Convide participantes na aba Campanhas.</p>}</div>}<p className="hint">A revelação só muda após salvar. Suas notas privadas continuam protegidas.</p></section>}
 <section className="panel"><p className="eyebrow">NO ACERVO</p>{editable?<Field label="Categorias (separadas por vírgula)" value={tagsText} onChange={v=>{setTagsText(v);field('tags',v.split(',').map(s=>s.trim()).filter(Boolean).slice(0,20))}}/>:<p>{draft.data.tags?.join(' · ')||singular[entry.kind]}</p>}{master&&entry.kind!=='map'&&<label className="secondary file-button"><Upload size={15}/> Adicionar imagem<input disabled={busy} type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0]);e.target.value=''}}/></label>}</section>
 {(personal||entry.kind==='script')&&<section className="panel"><p className="eyebrow">FICHA TÉCNICA</p>{editable&&<><Field label="Endereço da ficha (opcional)" value={draft.data.sheetUrl||''} onChange={v=>field('sheetUrl',v)} type="url" placeholder="https://…"/><Field label="ID da ficha no FichaAetheris" value={draft.data.sheetId||''} onChange={v=>field('sheetId',v)}/></>}{sheetUrl?<a className="secondary" href={sheetUrl} target="_blank" rel="noreferrer"><ExternalLink size={15}/> Abrir site de fichas</a>:<p className="hint">O mestre pode configurar o endereço do site em Mesa & configurações.</p>}{draft.data.sheetId&&<p className="hint">Ficha vinculada: #{draft.data.sheetId}. Selecione-a no outro site.</p>}{master&&draft.data.sheetSnapshot&&<p className="hint">Importado da ficha v{String(draft.data.sheetSnapshot.version||'')}. A lore permanece independente dos cálculos.</p>}</section>}
 <section className="panel"><p className="eyebrow">PÁGINAS CONECTADAS</p>{(draft.data.related||[]).map(id=>{const e=entries.find(x=>x.id===id);return e?<div key={id} className="related-link"><button onClick={()=>onOpen(e)}><LinkIcon size={14}/>{e.title}</button>{editable&&<button aria-label="Desvincular" onClick={()=>field('related',draft.data.related?.filter(x=>x!==id))}>×</button>}</div>:null})}{editable&&<Choice label="Conectar a outro registro" value="" onChange={id=>{if(id)field('related',[...(draft.data.related||[]),id])}} options={[{value:'',label:'Escolher registro…'},...entries.filter(e=>e.id!==entry.id&&!draft.data.related?.includes(e.id)).map(e=>({value:e.id,label:e.title}))]}/>}<p className="hint">Vínculos com páginas ainda secretas ficam ocultos para os jogadores.</p></section></aside></div>
 <AlertDialog open={deleting} onOpenChange={setDeleting}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Excluir “{entry.title}”?</AlertDialogTitle><AlertDialogDescription>O registro e suas imagens serão removidos. Exporte um backup nas configurações se quiser recuperá-lo depois.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async()=>{setBusy(true);try{await api('/entries/'+entry.id,{method:'DELETE'});onDelete(entry.id);toast.success('Registro excluído.')}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}}>Excluir registro</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>;
}
