import {useState} from 'react';
import {Users,Plus,Download,Upload,Link as LinkIcon,RefreshCw,KeyRound,ExternalLink} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {toast} from 'sonner';
import {Field,Empty} from './ui';
import {api,emptyEntry,type Person,type Settings,type Entry} from './types';
export default function SettingsPage({user,master,settings,people,reload,setSettings,onImport}:{user:Person;master:boolean;settings:Settings;people:Person[];reload:()=>Promise<void>;setSettings:(s:Settings)=>void;onImport:()=>Promise<void>}){
 const [url,setUrl]=useState(settings.sheetSiteUrl||''),[personModal,setPersonModal]=useState(false),[resetId,setResetId]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[current,setCurrent]=useState(''),[newPassword,setNewPassword]=useState(''),[busy,setBusy]=useState(false),[sheets,setSheets]=useState<any[]|null>(null),[integrationError,setIntegrationError]=useState('');
 async function job(fn:()=>Promise<void>){setBusy(true);try{await fn()}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 async function importSheet(s:any){await job(async()=>{const entries:Entry[]=await api('/entries');const old=entries.find(e=>e.kind==='character'&&e.data.sheetId===String(s.id));const record=old||{...emptyEntry('character'),title:s.name,summary:'História vinculada a uma ficha técnica.'};const body={...record,data:{...record.data,race:s.race,region:s.region,occupation:s.occupation,sheetId:String(s.id),sheetSnapshot:{version:s.version,level:s.level,username:s.username}}};await api(old?'/entries/'+old.id:'/entries',{method:old?'PUT':'POST',body:JSON.stringify(body)});await reload();toast.success(old?'Dados básicos atualizados. Sua história foi preservada.':'Personagem importado. Complete a história na aba Personagens.');})}
 return <div className="page"><p className="eyebrow">AO REDOR DA MESA</p><h1>{master?'Mesa & configurações':'Minha conta'}</h1><p>{master?'Convide seus jogadores, conecte as fichas e cuide do acervo.':'Seu acesso ao arquivo de Aetheris.'}</p><Tabs defaultValue={master?'players':'account'}><TabsList variant="line" className="settings-tabs">{master&&<><TabsTrigger value="players">Contas</TabsTrigger><TabsTrigger value="integration">FichaAetheris</TabsTrigger></>}<TabsTrigger value="backup">Meu backup</TabsTrigger><TabsTrigger value="account">Minha conta</TabsTrigger></TabsList>
 {master&&<><TabsContent value="players"><section className="panel"><div className="section-row"><div><h2>A sua mesa</h2><p>Cada jogador tem sua própria conta e só vê o conteúdo liberado.</p></div><button className="primary" onClick={()=>{setResetId('');setUsername('');setPassword('');setPersonModal(true)}}><Plus size={16}/> Adicionar jogador</button></div><Table><TableHeader><TableRow><TableHead>Nome</TableHead><TableHead>Papel</TableHead><TableHead>Acesso</TableHead></TableRow></TableHeader><TableBody>{people.map(p=><TableRow key={p.id}><TableCell><span className="user-cell"><Users size={16}/>{p.username}</span></TableCell><TableCell>{p.role==='master'?'Mestre':'Jogador'}</TableCell><TableCell>{p.role==='player'?<button className="text-button" onClick={()=>{setResetId(p.id);setUsername(p.username);setPassword('');setPersonModal(true)}}><KeyRound size={14}/> Redefinir senha</button>:<span className="hint">Controle do acervo</span>}</TableCell></TableRow>)}</TableBody></Table></section></TabsContent>
 <TabsContent value="integration"><div className="settings-grid"><section className="panel"><p className="eyebrow">DOIS SITES, UM PERSONAGEM</p><h2>Conecte a ficha à história.</h2><p>O FichaAetheris continua cuidando dos níveis e poderes. Aqui ficam as origens, os vínculos e a lore.</p><form onSubmit={e=>{e.preventDefault();void job(async()=>{const s=await api('/settings',{method:'PUT',body:JSON.stringify({sheetSiteUrl:url})});setSettings(s);toast.success('Endereço salvo.');})}}><Field label="Endereço do site de fichas no Render" value={url} onChange={setUrl} type="url" placeholder="https://seu-site.onrender.com"/><button className="primary" disabled={busy}><LinkIcon size={16}/> Salvar endereço</button></form><p className="hint">As contas são independentes. O link abre o outro site; selecione a ficha pelo nome ou ID.</p><a className="text-button" href="https://github.com/DaviCnd/FichaAetheris" target="_blank" rel="noreferrer">Repositório FichaAetheris <ExternalLink size={14}/></a></section><section className="panel"><p className="eyebrow">IMPORTAÇÃO OPCIONAL</p><h2>Dados básicos das fichas</h2><p>{settings.fichaConnected?'A conexão está configurada no servidor. Consulte as fichas e escolha o que importar.':'Para importar diretamente do Turso, configure FICHA_DATABASE_URL e FICHA_AUTH_TOKEN no servidor. As instruções estão no README do projeto.'}</p><button className="secondary" disabled={busy||!settings.fichaConnected} onClick={()=>{setIntegrationError('');void job(async()=>{try{setSheets(await api('/fichas'));}catch(e:any){setIntegrationError(e.message);throw e}})}}><RefreshCw size={15}/> Consultar fichas</button><p className="hint">Importa nome inicial, raça, região, profissão e referência da ficha. Não altera poderes, atributos ou o banco do outro site.</p>{integrationError&&<p className="error" role="alert">{integrationError}</p>}</section></div>{sheets&&<section className="panel mt-panel"><h2>Fichas disponíveis</h2>{sheets.length?<Table><TableHeader><TableRow><TableHead>Personagem</TableHead><TableHead>Jogador</TableHead><TableHead>Origem</TableHead><TableHead>Ação</TableHead></TableRow></TableHeader><TableBody>{sheets.map(s=><TableRow key={s.id}><TableCell>{s.name}<small className="block hint">#{s.id} · {s.race}</small></TableCell><TableCell>{s.username}</TableCell><TableCell>{s.region||'—'}</TableCell><TableCell><button className="secondary" disabled={busy} onClick={()=>void importSheet(s)}>Importar / atualizar</button></TableCell></TableRow>)}</TableBody></Table>:<Empty title="Nenhuma ficha encontrada" description="As fichas criadas no outro site aparecerão aqui."/>}</section>}</TabsContent>
 </>}<TabsContent value="backup"><div className="settings-grid"><section className="panel"><Download size={28}/><h2>Leve o seu mundo com você.</h2><p>Exporte registros, segredos, mapas, imagens e vínculos em um arquivo JSON. As senhas e sessões não são incluídas.</p><a href="/api/export" className="primary" download><Download size={16}/> Exportar backup</a></section><section className="panel"><Upload size={28}/><h2>Recupere páginas do acervo.</h2><p>A importação adiciona registros ausentes e preserva os existentes. Os registros recuperados ficam no seu acervo privado; revise suas permissões depois.</p><label className="secondary file-button"><Upload size={16}/>{busy?'Importando…':'Importar backup'}<input disabled={busy} type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(!f)return;void job(async()=>{if(f.size>45*1024*1024)throw new Error('O backup excede 45 MB.');const text=await f.text();JSON.parse(text);const r=await api('/import',{method:'POST',body:text});await onImport();toast.success(r.message)});e.target.value=''}}/></label><p className="hint">Contas e configurações de integração não são restauradas por este arquivo.</p></section></div></TabsContent>
 <TabsContent value="account"><section className="panel narrow"><h2>Segurança da sua conta</h2><p>Conectado como <strong>{user.username}</strong>.</p><form onSubmit={e=>{e.preventDefault();void job(async()=>{await api('/password',{method:'POST',body:JSON.stringify({current,password:newPassword})});setCurrent('');setNewPassword('');toast.success('Senha alterada. Outras sessões foram encerradas.');})}}><Field label="Senha atual" type="password" value={current} onChange={setCurrent} required autoComplete="current-password"/><Field label="Nova senha" type="password" value={newPassword} onChange={setNewPassword} required minLength={12} maxLength={128} autoComplete="new-password"/><button className="primary" disabled={busy}>Alterar senha</button></form></section></TabsContent></Tabs>
 <Dialog open={personModal} onOpenChange={setPersonModal}><DialogContent><DialogHeader><DialogTitle>{resetId?'Redefinir acesso':'Adicionar jogador'}</DialogTitle><DialogDescription>{resetId?`Defina uma nova senha para ${username}. As sessões antigas serão encerradas.`:'Crie uma conta e entregue a senha diretamente ao jogador.'}</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();void job(async()=>{await api(resetId?'/users/'+resetId+'/password':'/users',{method:resetId?'PUT':'POST',body:JSON.stringify({username,password})});setPersonModal(false);setPassword('');await reload();toast.success(resetId?'Senha redefinida.':'Jogador adicionado.');})}}>{!resetId&&<Field label="Nome de usuário" value={username} onChange={setUsername} minLength={2} maxLength={50} required autoComplete="off"/>}<Field label="Senha (mínimo 12 caracteres)" type="password" value={password} onChange={setPassword} minLength={12} maxLength={128} required autoComplete="new-password"/><button className="primary full" disabled={busy}>{resetId?'Redefinir senha':'Criar conta'}</button></form></DialogContent></Dialog>
 </div>;
}
