import React from 'react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Eye,Lock,Users} from 'lucide-react';
export function Choice({label,value,onChange,options,disabled=false}:{label:string;value:string;onChange:(s:string)=>void;options:{value:string;label:string}[];disabled?:boolean}){return <label className="field"><span>{label}</span><Select value={value||'__none'} onValueChange={v=>onChange(v==='__none'?'':v)} disabled={disabled}><SelectTrigger aria-label={label} className="w-full"><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value||'__none'} value={o.value||'__none'}>{o.label}</SelectItem>)}</SelectContent></Select></label>}
export function Field({label,value,onChange,multiline=false,...props}: {label:string;value:string;onChange:(s:string)=>void;multiline?:boolean;[key:string]:any}){return <label className="field"><span>{label}</span>{multiline?<Textarea value={value} onChange={e=>onChange(e.target.value)} {...props}/>:<Input value={value} onChange={e=>onChange(e.target.value)} {...props}/>}</label>}
export function Visibility({value}:{value:string}){const Icon=value==='all'?Eye:value==='selected'?Users:Lock;return <span className={'badge '+(value==='all'?'revealed':'')}><Icon size={12}/>{value==='all'?'Compartilhado':value==='selected'?'Participantes':'Privado'}</span>}
export function Prose({text}:{text:string}){return <div className="prose">{text.split('\n').map((line,i)=>line.startsWith('## ')?<h2 key={i}>{line.slice(3)}</h2>:line.startsWith('# ')?<h2 key={i}>{line.slice(2)}</h2>:line.startsWith('- ')?<p className="prose-list" key={i}>• {line.slice(2)}</p>:line?<p key={i}>{line.split(/(\*\*.*?\*\*)/g).map((p,j)=>p.startsWith('**')&&p.endsWith('**')?<strong key={j}>{p.slice(2,-2)}</strong>:p)}</p>:<div className="paragraph-gap" key={i}/> )}</div>}
export function Empty({title,description,children}:{title:string;description:string;children?:React.ReactNode}){return <div className="empty-state"><div className="empty-mark">◇</div><h2>{title}</h2><p>{description}</p>{children}</div>}
